### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by ArexanK** [OvenMagnetron/your-tribe-squad-page#3]
Wiki meer overzichtelijk maken en duidelijk jullie proces beschrijven 
Bij analyseren beschrijf analyse in verschillende fases zoals 

- analysefase 1:
- analysefase 2:
- analysefase 3:

- bouwfase 1:
- bouwfase 2:
- bouwfase 3:

**Comment by Jesse-Kramer** [comment]
We hebben de wiki verbeterd per fase
https://github.com/OvenMagnetron/your-tribe-squad-page/wiki
